import {
  base64UrlToBytes,
  bytesToBase64Url,
  containsAsciiControlCharacter,
} from "./encoding.js";
import { ZeroSheetCryptoError } from "./errors.js";
import { assertWorkbookKey } from "./workbook-key.js";

export const ENCRYPTED_CELL_FORMAT_VERSION = 1;
export const ENCRYPTED_CELL_PREFIX = "zs1";
export const CELL_NONCE_BYTES = 12;
export const CELL_GCM_TAG_BYTES = 16;
export const MAX_SERIALIZED_CELL_BYTES = 1024 * 1024;

/**
 * A spreadsheet engine needs the value's semantic kind after decryption.
 * Keeping a tagged union avoids turning numbers/booleans/formulas into strings
 * and accidentally changing calculation behavior.
 */
export type PlainCellValue =
  | { readonly kind: "blank" }
  | { readonly kind: "boolean"; readonly value: boolean }
  | { readonly kind: "number"; readonly value: number }
  | { readonly kind: "string"; readonly value: string }
  | { readonly kind: "formula"; readonly value: string };

/**
 * Coordinates are zero-based because Google Sheets API grids and most editor
 * internals use zero-based indexes. `sheetId` must be the stable sheet/tab ID,
 * not its renameable display title.
 */
export interface CellEncryptionContext {
  readonly workbookId: string;
  readonly sheetId: string;
  readonly row: number;
  readonly column: number;
  readonly keyVersion: number;
}

export interface EncryptedCellHeader {
  readonly formatVersion: 1;
  readonly keyVersion: number;
  readonly encryptedByteLength: number;
}

const textEncoder = new TextEncoder();
const textDecoder = new TextDecoder("utf-8", { fatal: true });

const VALUE_TAG_BLANK = 0;
const VALUE_TAG_FALSE = 1;
const VALUE_TAG_TRUE = 2;
const VALUE_TAG_NUMBER = 3;
const VALUE_TAG_STRING = 4;
const VALUE_TAG_FORMULA = 5;

/**
 * Recognize only ZeroSheet version markers. This is a display/routing helper,
 * not proof that the ciphertext is well formed or authentic.
 */
export function isEncryptedCell(value: unknown): value is string {
  return typeof value === "string" && /^zs[0-9]+:/u.test(value);
}

/** Parse the public version/key-version header without attempting decryption. */
export function inspectEncryptedCell(value: string): EncryptedCellHeader {
  const parts = value.split(":");
  if (parts.length !== 3) {
    throw new ZeroSheetCryptoError("MALFORMED_ENCRYPTED_CELL");
  }

  const [prefix, encodedKeyVersion, encodedPayload] = parts;
  if (prefix !== ENCRYPTED_CELL_PREFIX) {
    if (/^zs[0-9]+$/u.test(prefix ?? "")) {
      throw new ZeroSheetCryptoError("UNSUPPORTED_ENCRYPTED_FORMAT");
    }
    throw new ZeroSheetCryptoError("MALFORMED_ENCRYPTED_CELL");
  }

  if (!/^[1-9][0-9a-z]{0,6}$/u.test(encodedKeyVersion ?? "")) {
    throw new ZeroSheetCryptoError("MALFORMED_ENCRYPTED_CELL");
  }
  const keyVersion = Number.parseInt(encodedKeyVersion as string, 36);
  assertPositiveUint32(keyVersion, "MALFORMED_ENCRYPTED_CELL");
  if (keyVersion.toString(36) !== encodedKeyVersion) {
    throw new ZeroSheetCryptoError("MALFORMED_ENCRYPTED_CELL");
  }

  const encryptedBytes = base64UrlToBytes(encodedPayload ?? "");
  const encryptedByteLength = encryptedBytes.byteLength;
  encryptedBytes.fill(0);

  // AES-GCM appends a 16-byte tag, and every serialized plaintext contains at
  // least its one-byte type tag.
  if (
    encryptedByteLength < CELL_NONCE_BYTES + CELL_GCM_TAG_BYTES + 1 ||
    encryptedByteLength >
      CELL_NONCE_BYTES + CELL_GCM_TAG_BYTES + MAX_SERIALIZED_CELL_BYTES
  ) {
    throw new ZeroSheetCryptoError("MALFORMED_ENCRYPTED_CELL");
  }

  return {
    formatVersion: ENCRYPTED_CELL_FORMAT_VERSION,
    keyVersion,
    encryptedByteLength,
  };
}

/** Encrypt with a fresh 96-bit nonce generated by the browser CSPRNG. */
export async function encryptCell(
  key: CryptoKey,
  context: CellEncryptionContext,
  value: PlainCellValue,
): Promise<string> {
  const nonce = globalThis.crypto.getRandomValues(
    new Uint8Array(CELL_NONCE_BYTES),
  );
  try {
    return await encryptCellWithNonce(key, context, value, nonce);
  } finally {
    nonce.fill(0);
  }
}

/**
 * Deterministic inner operation used only by test vectors. Application code
 * must call `encryptCell`, because allowing UI/storage callers to choose nonces
 * would make catastrophic AES-GCM nonce reuse possible.
 */
export async function encryptCellWithNonce(
  key: CryptoKey,
  context: CellEncryptionContext,
  value: PlainCellValue,
  suppliedNonce: Uint8Array,
): Promise<string> {
  assertWorkbookKey(key);
  assertCellContext(context);
  if (suppliedNonce.byteLength !== CELL_NONCE_BYTES) {
    throw new ZeroSheetCryptoError("ENCRYPTION_FAILED");
  }

  const nonce = Uint8Array.from(suppliedNonce);
  const plaintext = serializeCellValue(value);
  const additionalData = createCellAdditionalData(context);

  try {
    const ciphertext = new Uint8Array(
      await globalThis.crypto.subtle.encrypt(
        {
          name: "AES-GCM",
          iv: nonce,
          additionalData,
          tagLength: CELL_GCM_TAG_BYTES * 8,
        },
        key,
        plaintext,
      ),
    );
    const payload = new Uint8Array(nonce.byteLength + ciphertext.byteLength);
    payload.set(nonce, 0);
    payload.set(ciphertext, nonce.byteLength);
    try {
      return `${ENCRYPTED_CELL_PREFIX}:${context.keyVersion.toString(36)}:${bytesToBase64Url(payload)}`;
    } finally {
      payload.fill(0);
      ciphertext.fill(0);
    }
  } catch (error) {
    if (error instanceof ZeroSheetCryptoError) {
      throw error;
    }
    throw new ZeroSheetCryptoError("ENCRYPTION_FAILED", error);
  } finally {
    nonce.fill(0);
    plaintext.fill(0);
    additionalData.fill(0);
  }
}

/**
 * Authenticate before decoding. Moving a valid ciphertext to another row,
 * column, sheet, workbook, or key version changes AAD and therefore fails.
 */
export async function decryptCell(
  key: CryptoKey,
  context: CellEncryptionContext,
  encryptedValue: string,
): Promise<PlainCellValue> {
  assertWorkbookKey(key);
  assertCellContext(context);
  const header = inspectEncryptedCell(encryptedValue);
  if (header.keyVersion !== context.keyVersion) {
    throw new ZeroSheetCryptoError("INVALID_CONTEXT");
  }

  const encodedPayload = encryptedValue.split(":")[2] as string;
  const payload = base64UrlToBytes(encodedPayload);
  const nonce = payload.slice(0, CELL_NONCE_BYTES);
  const ciphertext = payload.slice(CELL_NONCE_BYTES);
  const additionalData = createCellAdditionalData(context);

  try {
    const plaintext = new Uint8Array(
      await globalThis.crypto.subtle.decrypt(
        {
          name: "AES-GCM",
          iv: nonce,
          additionalData,
          tagLength: CELL_GCM_TAG_BYTES * 8,
        },
        key,
        ciphertext,
      ),
    );
    try {
      return deserializeCellValue(plaintext);
    } finally {
      plaintext.fill(0);
    }
  } catch (error) {
    if (error instanceof ZeroSheetCryptoError) {
      throw error;
    }
    throw new ZeroSheetCryptoError("CELL_AUTHENTICATION_FAILED", error);
  } finally {
    payload.fill(0);
    nonce.fill(0);
    ciphertext.fill(0);
    additionalData.fill(0);
  }
}

/** Return UTF-8 byte size without logging or retaining the plaintext value. */
export function serializedCellValueLength(value: PlainCellValue): number {
  const bytes = serializeCellValue(value);
  try {
    return bytes.byteLength;
  } finally {
    bytes.fill(0);
  }
}

function serializeCellValue(value: PlainCellValue): Uint8Array<ArrayBuffer> {
  switch (value.kind) {
    case "blank":
      return new Uint8Array([VALUE_TAG_BLANK]);
    case "boolean":
      return new Uint8Array([value.value ? VALUE_TAG_TRUE : VALUE_TAG_FALSE]);
    case "number": {
      if (!Number.isFinite(value.value)) {
        throw new ZeroSheetCryptoError("ENCRYPTION_FAILED");
      }
      const result = new Uint8Array(9);
      result[0] = VALUE_TAG_NUMBER;
      new DataView(result.buffer).setFloat64(1, value.value, false);
      return result;
    }
    case "string":
      return serializeTextValue(VALUE_TAG_STRING, value.value);
    case "formula":
      if (!value.value.startsWith("=") || value.value.length < 2) {
        throw new ZeroSheetCryptoError("ENCRYPTION_FAILED");
      }
      return serializeTextValue(VALUE_TAG_FORMULA, value.value);
  }
}

function serializeTextValue(
  tag: number,
  value: string,
): Uint8Array<ArrayBuffer> {
  const text = textEncoder.encode(value);
  if (text.byteLength + 1 > MAX_SERIALIZED_CELL_BYTES) {
    text.fill(0);
    throw new ZeroSheetCryptoError("ENCRYPTION_FAILED");
  }

  const result = new Uint8Array(text.byteLength + 1);
  result[0] = tag;
  result.set(text, 1);
  text.fill(0);
  return result;
}

function deserializeCellValue(plaintext: Uint8Array): PlainCellValue {
  if (
    plaintext.byteLength < 1 ||
    plaintext.byteLength > MAX_SERIALIZED_CELL_BYTES
  ) {
    throw new ZeroSheetCryptoError("MALFORMED_ENCRYPTED_CELL");
  }

  const tag = plaintext[0];
  const payload = plaintext.subarray(1);
  switch (tag) {
    case VALUE_TAG_BLANK:
      assertEmptyPayload(payload);
      return { kind: "blank" };
    case VALUE_TAG_FALSE:
      assertEmptyPayload(payload);
      return { kind: "boolean", value: false };
    case VALUE_TAG_TRUE:
      assertEmptyPayload(payload);
      return { kind: "boolean", value: true };
    case VALUE_TAG_NUMBER: {
      if (payload.byteLength !== 8) {
        throw new ZeroSheetCryptoError("MALFORMED_ENCRYPTED_CELL");
      }
      const numericValue = new DataView(
        payload.buffer,
        payload.byteOffset,
        payload.byteLength,
      ).getFloat64(0, false);
      if (!Number.isFinite(numericValue)) {
        throw new ZeroSheetCryptoError("MALFORMED_ENCRYPTED_CELL");
      }
      return {
        kind: "number",
        value: numericValue,
      };
    }
    case VALUE_TAG_STRING:
      return { kind: "string", value: decodeText(payload) };
    case VALUE_TAG_FORMULA: {
      const formula = decodeText(payload);
      if (!formula.startsWith("=") || formula.length < 2) {
        throw new ZeroSheetCryptoError("MALFORMED_ENCRYPTED_CELL");
      }
      return { kind: "formula", value: formula };
    }
    default:
      throw new ZeroSheetCryptoError("MALFORMED_ENCRYPTED_CELL");
  }
}

function decodeText(bytes: Uint8Array): string {
  try {
    return textDecoder.decode(bytes);
  } catch (error) {
    throw new ZeroSheetCryptoError("MALFORMED_ENCRYPTED_CELL", error);
  }
}

function assertEmptyPayload(payload: Uint8Array): void {
  if (payload.byteLength !== 0) {
    throw new ZeroSheetCryptoError("MALFORMED_ENCRYPTED_CELL");
  }
}

function createCellAdditionalData(
  context: CellEncryptionContext,
): Uint8Array<ArrayBuffer> {
  // A fixed-order JSON array is unambiguous and compact enough for AAD, which
  // is authenticated but not stored in every cell. IDs may contain punctuation
  // without creating delimiter collisions.
  return textEncoder.encode(
    JSON.stringify([
      "zerosheet:cell",
      ENCRYPTED_CELL_FORMAT_VERSION,
      context.workbookId,
      context.sheetId,
      context.row,
      context.column,
      context.keyVersion,
    ]),
  );
}

function assertCellContext(context: CellEncryptionContext): void {
  assertContextIdentifier(context.workbookId);
  assertContextIdentifier(context.sheetId);
  assertPositiveUint32(context.keyVersion, "INVALID_CONTEXT");

  if (
    !Number.isInteger(context.row) ||
    context.row < 0 ||
    context.row > 0xffff_ffff ||
    !Number.isInteger(context.column) ||
    context.column < 0 ||
    context.column > 0xffff_ffff
  ) {
    throw new ZeroSheetCryptoError("INVALID_CONTEXT");
  }
}

function assertContextIdentifier(value: string): void {
  if (
    value.length < 1 ||
    value.length > 512 ||
    value.trim() !== value ||
    containsAsciiControlCharacter(value)
  ) {
    throw new ZeroSheetCryptoError("INVALID_CONTEXT");
  }
}

function assertPositiveUint32(
  value: number,
  code: "INVALID_CONTEXT" | "MALFORMED_ENCRYPTED_CELL",
): void {
  if (!Number.isInteger(value) || value < 1 || value > 0xffff_ffff) {
    throw new ZeroSheetCryptoError(code);
  }
}
