-- ZeroSheet OIDC BFF authentication schema
-- =========================================
--
-- Keycloak's database answers how an identity authenticates. These tables live
-- in the separate ZeroSheet database and answer which product user that
-- verified identity maps to and which opaque browser sessions are currently
-- valid. No Keycloak password or bearer token belongs in this schema.
--
-- This migration is intentionally append-only and idempotent for the learning
-- environment. Production deployments will record and apply immutable files in
-- the same order before starting a new API release.

BEGIN;

CREATE TABLE IF NOT EXISTS schema_migrations (
  version text PRIMARY KEY,
  applied_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_users (
  -- IDs are generated by the API rather than copied from Keycloak. This keeps
  -- product records stable if an administrator later migrates identity realms.
  id uuid PRIMARY KEY,
  primary_email text NOT NULL CHECK (length(primary_email) BETWEEN 3 AND 320),
  display_name text NOT NULL CHECK (length(display_name) BETWEEN 1 AND 200),
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS external_identities (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES product_users(id) ON DELETE CASCADE,

  -- OIDC defines the pair (issuer, subject) as the durable identity key. Email
  -- is mutable and must never be used for automatic account linking.
  issuer text NOT NULL CHECK (length(issuer) BETWEEN 1 AND 2_048),
  subject text NOT NULL CHECK (length(subject) BETWEEN 1 AND 255),
  email_at_provider text NOT NULL CHECK (
    length(email_at_provider) BETWEEN 3 AND 320
  ),
  email_verified boolean NOT NULL,
  created_at timestamp with time zone NOT NULL,
  last_login_at timestamp with time zone NOT NULL,

  CONSTRAINT external_identities_issuer_subject_unique
    UNIQUE (issuer, subject),
  CONSTRAINT external_identities_user_issuer_unique
    UNIQUE (user_id, issuer)
);

CREATE TABLE IF NOT EXISTS oidc_login_transactions (
  -- The browser receives a random selector; only its SHA-256 digest is stored.
  -- A database reader therefore cannot directly replay the cookie.
  selector_hash character(64) PRIMARY KEY,
  state text NOT NULL UNIQUE CHECK (length(state) BETWEEN 32 AND 512),
  nonce text NOT NULL CHECK (length(nonce) BETWEEN 32 AND 512),
  code_verifier text NOT NULL CHECK (length(code_verifier) BETWEEN 43 AND 128),
  created_at timestamp with time zone NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  CONSTRAINT oidc_login_transaction_time_order
    CHECK (expires_at > created_at)
);

CREATE INDEX IF NOT EXISTS oidc_login_transactions_expires_at_idx
  ON oidc_login_transactions (expires_at);

CREATE TABLE IF NOT EXISTS user_sessions (
  -- Session tokens are high-entropy bearer credentials. As with login
  -- transactions, PostgreSQL retains only a one-way selector.
  selector_hash character(64) PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES product_users(id) ON DELETE CASCADE,
  created_at timestamp with time zone NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  CONSTRAINT user_session_time_order CHECK (expires_at > created_at)
);

CREATE INDEX IF NOT EXISTS user_sessions_user_id_idx
  ON user_sessions (user_id);

CREATE INDEX IF NOT EXISTS user_sessions_expires_at_idx
  ON user_sessions (expires_at);

INSERT INTO schema_migrations (version)
VALUES ('001_oidc_bff_authentication')
ON CONFLICT (version) DO NOTHING;

COMMIT;
