#!/usr/bin/env bash

# Verify the complete authentication-to-authorization enforcement path.
#
# Prerequisites: the authorization stack and API must be running. This script
# creates two short-lived product sessions and an active workbook through the
# public API, proves allow and deny behavior through OpenFGA plus the composed
# API PEP, then removes all verification state even when a check fails.

set -euo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
compose_file="${repository_root}/infra/compose.yaml"
environment_file="${repository_root}/.env"
openfga_environment_file="${repository_root}/.env.openfga"
verification_directory="$(mktemp -d)"

if [[ ! -f "${environment_file}" ]]; then
  echo "Missing ${environment_file}. Copy .env.example to .env first." >&2
  exit 1
fi

if [[ ! -f "${openfga_environment_file}" ]]; then
  echo "Missing ${openfga_environment_file}." >&2
  echo "Run pnpm infra:authorization:provision first." >&2
  exit 1
fi

# These files contain developer-controlled local values and generated non-secret
# IDs. Exporting them makes curl and Docker Compose address the same boundary as
# the running API.
set -a
# shellcheck disable=SC1090 -- paths are calculated and intentionally local.
source "${environment_file}"
# shellcheck disable=SC1090 -- generated by the trusted provisioner above.
source "${openfga_environment_file}"
set +a

new_uuid() {
  node --input-type=module --eval 'console.log(crypto.randomUUID())'
}

allowed_user_id="$(new_uuid)"
denied_user_id="$(new_uuid)"
allowed_session_token="authorization-allowed-$(new_uuid)"
denied_session_token="authorization-denied-$(new_uuid)"
allowed_selector_hash="$(printf '%s' "${allowed_session_token}" | shasum -a 256 | awk '{print $1}')"
denied_selector_hash="$(printf '%s' "${denied_session_token}" | shasum -a 256 | awk '{print $1}')"
organization_id=""
workbook_id=""

if [[ ! "${OPENFGA_STORE_ID}" =~ ^[0-9A-HJKMNP-TV-Z]{26}$ ]] ||
  [[ ! "${OPENFGA_AUTHORIZATION_MODEL_ID}" =~ ^[0-9A-HJKMNP-TV-Z]{26}$ ]] ||
  [[ ! "${allowed_selector_hash}" =~ ^[0-9a-f]{64}$ ]] ||
  [[ ! "${denied_selector_hash}" =~ ^[0-9a-f]{64}$ ]]; then
  echo "Generated verification identifiers have an unexpected format." >&2
  exit 1
fi

run_zerosheet_sql() {
  docker compose \
    --env-file "${environment_file}" \
    --file "${compose_file}" \
    exec --no-TTY postgres \
    sh -c 'PGPASSWORD="$ZEROSHEET_DB_PASSWORD" exec psql --tuples-only --no-align --set=ON_ERROR_STOP=1 --username "$ZEROSHEET_DB_USER" --dbname "$ZEROSHEET_DB_NAME" "$@"' \
    sh \
    "$@"
}

openfga_write() {
  local body="$1"

  curl --fail --silent --show-error \
    --request POST \
    --header "Authorization: Bearer ${OPENFGA_PRESHARED_KEY}" \
    --header "Content-Type: application/json" \
    --data "${body}" \
    "${OPENFGA_API_URL}/stores/${OPENFGA_STORE_ID}/write" \
    >/dev/null
}

cleanup() {
  # Cleanup must never hide the original verifier failure. Tuple deletion uses
  # Ignore because an interrupted API request can leave only part of the graph.
  set +e

  if [[ -n "${organization_id}" ]]; then
    tuple_keys=(
      "{\"user\":\"user:${allowed_user_id}\",\"relation\":\"owner\",\"object\":\"organization:${organization_id}\"}"
    )
    if [[ -n "${workbook_id}" ]]; then
      tuple_keys+=(
        "{\"user\":\"organization:${organization_id}\",\"relation\":\"organization\",\"object\":\"workbook:${workbook_id}\"}"
        "{\"user\":\"user:${allowed_user_id}\",\"relation\":\"owner\",\"object\":\"workbook:${workbook_id}\"}"
      )
    fi
    tuple_json="$(IFS=,; echo "${tuple_keys[*]}")"
    openfga_write "{\"authorization_model_id\":\"${OPENFGA_AUTHORIZATION_MODEL_ID}\",\"deletes\":{\"tuple_keys\":[${tuple_json}],\"on_missing\":\"ignore\"}}" 2>/dev/null
  fi

  run_zerosheet_sql --command "
    DELETE FROM organizations WHERE id = NULLIF('${organization_id}', '')::uuid;
    DELETE FROM relationship_outbox
    WHERE writes::text LIKE '%${allowed_user_id}%'
       OR deletes::text LIKE '%${allowed_user_id}%';
    DELETE FROM product_users WHERE id IN ('${allowed_user_id}', '${denied_user_id}');
  " >/dev/null 2>&1
  rm -rf -- "${verification_directory}"
}

trap cleanup EXIT

run_zerosheet_sql --command "
  INSERT INTO product_users (id, primary_email, display_name, created_at, updated_at)
  VALUES
    ('${allowed_user_id}', 'allowed-verifier@zerosheet.local', 'Allowed Verifier', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('${denied_user_id}', 'denied-verifier@zerosheet.local', 'Denied Verifier', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
  ON CONFLICT (id) DO UPDATE SET updated_at = EXCLUDED.updated_at;

  INSERT INTO user_sessions (selector_hash, user_id, created_at, expires_at)
  VALUES
    ('${allowed_selector_hash}', '${allowed_user_id}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '10 minutes'),
    ('${denied_selector_hash}', '${denied_user_id}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '10 minutes')
  ON CONFLICT (selector_hash) DO UPDATE
    SET user_id = EXCLUDED.user_id,
        created_at = EXCLUDED.created_at,
        expires_at = EXCLUDED.expires_at;
" >/dev/null

json_id() {
  node --input-type=module --eval '
    import fs from "node:fs";
    const body = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
    if (typeof body.id !== "string") throw new Error("Response has no id");
    process.stdout.write(body.id);
  ' "$1"
}

# The PIP now requires active product metadata. Creating that metadata through
# public APIs also proves organization creation and OpenFGA tuple provisioning
# pass through the same PEP being verified.
organization_status="$(curl --silent --show-error \
  --output "${verification_directory}/organization.json" \
  --write-out '%{http_code}' \
  --request POST \
  --header "Cookie: zerosheet_session=${allowed_session_token}" \
  --header "Content-Type: application/json" \
  --data '{"name":"Authorization Foundation"}' \
  "${ZEROSHEET_API_URL}/organizations")"

if [[ "${organization_status}" != "201" ]]; then
  echo "FAIL: could not create active organization context (HTTP ${organization_status})." >&2
  exit 1
fi
organization_id="$(json_id "${verification_directory}/organization.json")"

workbook_status="$(curl --silent --show-error \
  --output "${verification_directory}/workbook.json" \
  --write-out '%{http_code}' \
  --request POST \
  --header "Cookie: zerosheet_session=${allowed_session_token}" \
  --header "Content-Type: application/json" \
  --data '{"name":"Authorization Workbook"}' \
  "${ZEROSHEET_API_URL}/organizations/${organization_id}/workbooks")"

if [[ "${workbook_status}" != "201" ]]; then
  echo "FAIL: could not create active workbook context (HTTP ${workbook_status})." >&2
  exit 1
fi
workbook_id="$(json_id "${verification_directory}/workbook.json")"

check_openfga() {
  local user_id="$1"
  local expected="$2"

  curl --fail --silent --show-error \
    --request POST \
    --header "Authorization: Bearer ${OPENFGA_PRESHARED_KEY}" \
    --header "Content-Type: application/json" \
    --data "{\"authorization_model_id\":\"${OPENFGA_AUTHORIZATION_MODEL_ID}\",\"tuple_key\":{\"user\":\"user:${user_id}\",\"relation\":\"can_view\",\"object\":\"workbook:${workbook_id}\"},\"consistency\":\"HIGHER_CONSISTENCY\"}" \
    "${OPENFGA_API_URL}/stores/${OPENFGA_STORE_ID}/check" |
    EXPECTED_ALLOWED="${expected}" node --input-type=module --eval '
      let body = "";
      for await (const chunk of process.stdin) body += chunk;
      const response = JSON.parse(body);
      const expected = process.env.EXPECTED_ALLOWED === "true";

      if (response.allowed !== expected) {
        throw new Error(`Expected allowed=${expected}; received ${response.allowed}`);
      }
    '
}

check_openfga "${allowed_user_id}" true
check_openfga "${denied_user_id}" false

api_base_url="${ZEROSHEET_API_URL}"

allowed_status="$(
  curl --silent --show-error \
    --output "${verification_directory}/allowed.json" \
    --write-out '%{http_code}' \
    --header "Cookie: zerosheet_session=${allowed_session_token}" \
    "${api_base_url}/workbooks/${workbook_id}/access"
)"

denied_status="$(
  curl --silent --show-error \
    --output "${verification_directory}/denied.json" \
    --write-out '%{http_code}' \
    --header "Cookie: zerosheet_session=${denied_session_token}" \
    "${api_base_url}/workbooks/${workbook_id}/access"
)"

anonymous_status="$(
  curl --silent --show-error \
    --output "${verification_directory}/anonymous.json" \
    --write-out '%{http_code}' \
    "${api_base_url}/workbooks/${workbook_id}/access"
)"

if [[ "${allowed_status}" != "200" ]] ||
  ! grep --quiet '"allowed":true' "${verification_directory}/allowed.json"; then
  echo "FAIL: the PEP did not return the explicitly allowed workbook access." >&2
  exit 1
fi

if [[ "${denied_status}" != "403" ]] ||
  ! grep --quiet '"error":"forbidden"' "${verification_directory}/denied.json"; then
  echo "FAIL: the PEP did not deny the unrelated authenticated user." >&2
  exit 1
fi

if [[ "${anonymous_status}" != "401" ]] ||
  ! grep --quiet '"authenticated":false' \
    "${verification_directory}/anonymous.json"; then
  echo "FAIL: the PEP did not reject an unauthenticated browser." >&2
  exit 1
fi

echo "PASS: OpenFGA returns allow for the owner and deny for an unrelated user."
echo "PASS: the API derives the principal from its opaque session and enforces the decision with HTTP 200/403."
echo "PASS: an anonymous request is rejected before OpenFGA authorization."
