/**
 * Runtime configuration is parsed once, before the HTTP server starts.
 *
 * Authentication configuration is part of the security boundary: accepting a
 * typo as an empty client secret or treating an arbitrary string as a URL can
 * turn a safe OIDC flow into a confusing runtime failure. These helpers keep
 * validation small and dependency-free while producing errors that name the
 * exact variable a developer must fix.
 */

export interface DatabaseConfig {
  host: string;
  port: number;
  database: string;
  user: string;
  password: string;
  useTls: boolean;
}

export interface OidcConfig {
  issuerUrl: URL;
  allowInsecureHttp: boolean;
  clientId: string;
  clientSecret: string;
  callbackUrl: URL;
  postLogoutRedirectUrl: URL;
}

export interface AuthorizationConfig {
  apiUrl: URL;
  allowInsecureHttp: boolean;
  storeId: string;
  authorizationModelId: string;
  apiToken: string;
}

export interface ContextualAuthorizationConfig {
  apiUrl: URL;
  allowInsecureHttp: boolean;
  requestTimeoutMs: number;
}

export interface AuthLifetimeConfig {
  loginTransactionSeconds: number;
  sessionSeconds: number;
}

export interface AuthCookieConfig {
  secure: boolean;
  loginTransactionName: string;
  sessionName: string;
  googleStorageTransactionName: string;
}

/**
 * Google storage consent is not identity federation. Keeping a discriminated
 * disabled state lets the IAM lab run without fake OAuth secrets while making
 * every credential mandatory before the storage routes can be enabled.
 */
export type GoogleStorageOAuthConfig =
  | {
      enabled: false;
      callbackUrl: URL;
      transactionSeconds: number;
    }
  | {
      enabled: true;
      callbackUrl: URL;
      transactionSeconds: number;
      clientId: string;
      clientSecret: string;
      tokenEncryptionKey: Uint8Array;
    };

export interface RuntimeConfig {
  host: string;
  port: number;
  logLevel: string;
  webUrl: URL;
  database: DatabaseConfig;
  oidc: OidcConfig;
  authorization: AuthorizationConfig;
  contextualAuthorization: ContextualAuthorizationConfig;
  googleStorage: GoogleStorageOAuthConfig;
  authLifetimes: AuthLifetimeConfig;
  authCookies: AuthCookieConfig;
}

function required(environment: NodeJS.ProcessEnv, name: string): string {
  const value = environment[name]?.trim();

  if (!value) {
    throw new Error(`${name} is required`);
  }

  return value;
}

function positiveInteger(
  environment: NodeJS.ProcessEnv,
  name: string,
  fallback?: number,
): number {
  const rawValue = environment[name]?.trim();

  if (!rawValue && fallback !== undefined) {
    return fallback;
  }

  const value = Number.parseInt(rawValue ?? "", 10);

  if (!Number.isSafeInteger(value) || value <= 0) {
    throw new Error(`${name} must be a positive integer`);
  }

  return value;
}

function booleanValue(
  environment: NodeJS.ProcessEnv,
  name: string,
  fallback: boolean,
): boolean {
  const rawValue = environment[name]?.trim().toLowerCase();

  if (!rawValue) {
    return fallback;
  }

  if (rawValue === "true") {
    return true;
  }

  if (rawValue === "false") {
    return false;
  }

  throw new Error(`${name} must be either true or false`);
}

function urlValue(environment: NodeJS.ProcessEnv, name: string): URL {
  const value = required(environment, name);

  try {
    return new URL(value);
  } catch {
    throw new Error(`${name} must be an absolute URL`);
  }
}

function isLoopbackHostname(hostname: string): boolean {
  return (
    hostname === "localhost" || hostname === "127.0.0.1" || hostname === "[::1]"
  );
}

function openFgaIdentifier(
  environment: NodeJS.ProcessEnv,
  name: string,
): string {
  const value = required(environment, name);

  // OpenFGA store and model identifiers are 26-character ULIDs. Failing during
  // startup gives a clear provisioning instruction instead of sending every
  // authorization check to an invalid or placeholder boundary.
  if (!/^[0-9A-HJKMNP-TV-Z]{26}$/u.test(value)) {
    throw new Error(
      `${name} must be an OpenFGA ULID generated by pnpm infra:authorization:provision`,
    );
  }

  return value;
}

/**
 * Production cookies use the `__Host-` prefix. Supporting browsers enforce
 * that these cookies are Secure, host-only, and scoped to `/`, which prevents
 * a sibling subdomain from planting a competing authentication cookie. Local
 * HTTP cannot use Secure cookies, so the learning environment uses explicit
 * development-only names instead.
 */
function cookieNames(
  secure: boolean,
): Pick<
  AuthCookieConfig,
  "loginTransactionName" | "sessionName" | "googleStorageTransactionName"
> {
  if (secure) {
    return {
      loginTransactionName: "__Host-zerosheet_oidc_transaction",
      sessionName: "__Host-zerosheet_session",
      googleStorageTransactionName:
        "__Host-zerosheet_google_storage_transaction",
    };
  }

  return {
    loginTransactionName: "zerosheet_oidc_transaction",
    sessionName: "zerosheet_session",
    googleStorageTransactionName: "zerosheet_google_storage_transaction",
  };
}

function base64UrlKey(
  environment: NodeJS.ProcessEnv,
  name: string,
): Uint8Array {
  const value = required(environment, name);
  if (!/^[A-Za-z0-9_-]{43}$/u.test(value)) {
    throw new Error(`${name} must be unpadded base64url for exactly 32 bytes`);
  }

  const bytes = Buffer.from(value, "base64url");
  if (bytes.byteLength !== 32 || bytes.toString("base64url") !== value) {
    bytes.fill(0);
    throw new Error(`${name} must be unpadded base64url for exactly 32 bytes`);
  }
  return new Uint8Array(bytes);
}

export function loadRuntimeConfig(
  environment: NodeJS.ProcessEnv = process.env,
): RuntimeConfig {
  const nodeEnvironment = environment.NODE_ENV?.trim() || "development";
  const secureCookies = booleanValue(
    environment,
    "ZEROSHEET_COOKIE_SECURE",
    nodeEnvironment === "production",
  );

  if (nodeEnvironment === "production" && !secureCookies) {
    throw new Error(
      "ZEROSHEET_COOKIE_SECURE must be true when NODE_ENV is production",
    );
  }

  const apiUrl = urlValue(environment, "ZEROSHEET_API_URL");
  const webUrl = urlValue(environment, "ZEROSHEET_WEB_URL");
  const issuerUrl = urlValue(environment, "ZEROSHEET_OIDC_ISSUER_URL");
  const openFgaApiUrl = urlValue(environment, "OPENFGA_API_URL");
  const opaApiUrl = urlValue(environment, "OPA_API_URL");
  const names = cookieNames(secureCookies);
  const googleStorageEnabled = booleanValue(
    environment,
    "GOOGLE_STORAGE_OAUTH_ENABLED",
    false,
  );
  const googleStorageBase = {
    callbackUrl: new URL("/google/storage/callback", apiUrl),
    transactionSeconds: positiveInteger(
      environment,
      "GOOGLE_STORAGE_OAUTH_TRANSACTION_TTL_SECONDS",
      600,
    ),
  };

  if (
    nodeEnvironment === "production" &&
    (apiUrl.protocol !== "https:" || webUrl.protocol !== "https:")
  ) {
    throw new Error(
      "ZEROSHEET_API_URL and ZEROSHEET_WEB_URL must use HTTPS when NODE_ENV is production",
    );
  }

  /**
   * OIDC normally requires HTTPS. The only exception is our local learning
   * server bound to the loopback device; allowing HTTP for a LAN or production
   * hostname would expose authorization codes and tokens to interception.
   */
  const allowInsecureHttp =
    nodeEnvironment !== "production" &&
    issuerUrl.protocol === "http:" &&
    isLoopbackHostname(issuerUrl.hostname);

  if (issuerUrl.protocol !== "https:" && !allowInsecureHttp) {
    throw new Error(
      "ZEROSHEET_OIDC_ISSUER_URL must use HTTPS outside the local loopback development environment",
    );
  }

  /**
   * The local OpenFGA port is loopback-only and may use HTTP. A remote PDP must
   * use HTTPS because its bearer credential and allow/deny questions reveal
   * security-sensitive relationship metadata. Workload mTLS replaces this
   * local exception in a later milestone.
   */
  const allowInsecureOpenFgaHttp =
    nodeEnvironment !== "production" &&
    openFgaApiUrl.protocol === "http:" &&
    isLoopbackHostname(openFgaApiUrl.hostname);

  if (openFgaApiUrl.protocol !== "https:" && !allowInsecureOpenFgaHttp) {
    throw new Error(
      "OPENFGA_API_URL must use HTTPS outside the local loopback development environment",
    );
  }

  /**
   * OPA receives account/tenant status and the OpenFGA decision, all of which
   * are sensitive authorization metadata. Plain HTTP is therefore allowed
   * only for the loopback-bound local lab, matching the OpenFGA boundary.
   */
  const allowInsecureOpaHttp =
    nodeEnvironment !== "production" &&
    opaApiUrl.protocol === "http:" &&
    isLoopbackHostname(opaApiUrl.hostname);

  if (opaApiUrl.protocol !== "https:" && !allowInsecureOpaHttp) {
    throw new Error(
      "OPA_API_URL must use HTTPS outside the local loopback development environment",
    );
  }

  return {
    host: environment.API_HOST?.trim() || "127.0.0.1",
    port: positiveInteger(environment, "API_PORT", 3001),
    logLevel: environment.LOG_LEVEL?.trim() || "info",
    webUrl,
    database: {
      host: environment.ZEROSHEET_DB_HOST?.trim() || "127.0.0.1",
      port: positiveInteger(environment, "POSTGRES_HOST_PORT", 5434),
      database: required(environment, "ZEROSHEET_DB_NAME"),
      user: required(environment, "ZEROSHEET_DB_USER"),
      password: required(environment, "ZEROSHEET_DB_PASSWORD"),
      useTls: booleanValue(environment, "ZEROSHEET_DB_TLS", false),
    },
    oidc: {
      issuerUrl,
      allowInsecureHttp,
      clientId: required(environment, "KEYCLOAK_BFF_CLIENT_ID"),
      clientSecret: required(environment, "KEYCLOAK_BFF_CLIENT_SECRET"),
      callbackUrl: new URL("/auth/callback", apiUrl),
      postLogoutRedirectUrl: new URL("/", webUrl),
    },
    authorization: {
      apiUrl: openFgaApiUrl,
      allowInsecureHttp: allowInsecureOpenFgaHttp,
      storeId: openFgaIdentifier(environment, "OPENFGA_STORE_ID"),
      authorizationModelId: openFgaIdentifier(
        environment,
        "OPENFGA_AUTHORIZATION_MODEL_ID",
      ),
      apiToken: required(environment, "OPENFGA_PRESHARED_KEY"),
    },
    contextualAuthorization: {
      apiUrl: opaApiUrl,
      allowInsecureHttp: allowInsecureOpaHttp,
      requestTimeoutMs: positiveInteger(
        environment,
        "OPA_REQUEST_TIMEOUT_MS",
        5_000,
      ),
    },
    googleStorage: googleStorageEnabled
      ? {
          enabled: true,
          ...googleStorageBase,
          clientId: required(environment, "GOOGLE_STORAGE_OAUTH_CLIENT_ID"),
          clientSecret: required(
            environment,
            "GOOGLE_STORAGE_OAUTH_CLIENT_SECRET",
          ),
          tokenEncryptionKey: base64UrlKey(
            environment,
            "GOOGLE_STORAGE_TOKEN_ENCRYPTION_KEY",
          ),
        }
      : { enabled: false, ...googleStorageBase },
    authLifetimes: {
      loginTransactionSeconds: positiveInteger(
        environment,
        "ZEROSHEET_OIDC_TRANSACTION_TTL_SECONDS",
        600,
      ),
      sessionSeconds: positiveInteger(
        environment,
        "ZEROSHEET_SESSION_TTL_SECONDS",
        28_800,
      ),
    },
    authCookies: {
      secure: secureCookies,
      ...names,
    },
  };
}
